### ISSUE TITLE
Can this work with CAD/BIM programs?

### ISSUE THREAD

**Issue by luzpaz** [FZJ-IEK3-VSA/HiSim#3]
Is that on the roadmap?

**Comment by noah80** [comment]
Not yet. We don't currently have a need to implement such functionality, but it shouldn't be diffcult to create a connector if you want to use this. We would be very happy to accept a pull request.

**Comment by yorikvanhavre** [comment]
Integrating this into https://github.com/FreeCAD/FreeCAD wouldn't be difficult i think.. it would be mostly a question of identifying how an HiSim setup could be obtained from a #FreeCAD BIM model, ie. what objects should carry what kind of property (same for #BlenderBIM i guess). If anyone is interested in working on this, I'd be willing to help.

**Comment by DuncanLithgow** [comment]
I would be inclined to focus on both HiSim & FreeCAD supporting exchange of relevant geometry & properties with reference to the IFC schema rather than each to their own schema. Then FreeCAD can run HiSim on any good IFC file and HiSim is designed to make it as pain free as possible. Maybe the IFC schema is not the best for this, then something else that is an open data schema and seeing broad adoption (BHoM, or Google Digital Building schema). Just my two cents.
